/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vendinglegagzx;

import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author SCC-COLLEGE
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        setIconImage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        coke = new javax.swing.JButton();
        jazz = new javax.swing.JButton();
        sprite = new javax.swing.JButton();
        sevenUp = new javax.swing.JButton();
        fanta = new javax.swing.JButton();
        summit = new javax.swing.JButton();
        pepsi = new javax.swing.JButton();
        sparkle = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        showProduct = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        showPrice = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        showQty = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        showQty1 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PRISM");

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(null);

        name.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        name.setForeground(new java.awt.Color(255, 255, 0));
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText("PROFILE USER: ARCAMO");
        jPanel1.add(name);
        name.setBounds(380, 30, 240, 20);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Verdana", 1, 13)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 0));
        jTextArea1.setRows(5);
        jTextArea1.setText("          \n                         PRICE LIST:\n\n COKE    php12.00     JAZZ        php8.00\n SPRITE php11.00     7 UP         php9.00\n FANTA  php11.00     SUMMIT   php10.00\n PEPSI   php12.00     SPARKLE  php8.00\n\n\n\n");
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(50, 350, 300, 180);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("SELECT PRODUCT");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 10, 410, 50);

        coke.setBackground(new java.awt.Color(217, 78, 78));
        coke.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        coke.setText("COKE");
        coke.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        coke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cokeActionPerformed(evt);
            }
        });
        jPanel1.add(coke);
        coke.setBounds(40, 70, 150, 50);

        jazz.setBackground(new java.awt.Color(255, 153, 204));
        jazz.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        jazz.setText("JAZZ");
        jazz.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jazz.setMaximumSize(new java.awt.Dimension(59, 23));
        jazz.setMinimumSize(new java.awt.Dimension(59, 23));
        jazz.setPreferredSize(new java.awt.Dimension(59, 23));
        jazz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jazzActionPerformed(evt);
            }
        });
        jPanel1.add(jazz);
        jazz.setBounds(210, 70, 150, 50);

        sprite.setBackground(new java.awt.Color(96, 215, 155));
        sprite.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        sprite.setText("SPRITE");
        sprite.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        sprite.setMaximumSize(new java.awt.Dimension(59, 23));
        sprite.setMinimumSize(new java.awt.Dimension(59, 23));
        sprite.setPreferredSize(new java.awt.Dimension(59, 23));
        sprite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spriteActionPerformed(evt);
            }
        });
        jPanel1.add(sprite);
        sprite.setBounds(40, 140, 150, 50);

        sevenUp.setBackground(new java.awt.Color(105, 215, 68));
        sevenUp.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        sevenUp.setText("7 UP");
        sevenUp.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        sevenUp.setMaximumSize(new java.awt.Dimension(59, 23));
        sevenUp.setMinimumSize(new java.awt.Dimension(59, 23));
        sevenUp.setPreferredSize(new java.awt.Dimension(59, 23));
        sevenUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenUpActionPerformed(evt);
            }
        });
        jPanel1.add(sevenUp);
        sevenUp.setBounds(210, 140, 150, 50);

        fanta.setBackground(new java.awt.Color(255, 184, 79));
        fanta.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        fanta.setText("FANTA");
        fanta.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        fanta.setMaximumSize(new java.awt.Dimension(59, 23));
        fanta.setMinimumSize(new java.awt.Dimension(59, 23));
        fanta.setPreferredSize(new java.awt.Dimension(59, 23));
        fanta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fantaActionPerformed(evt);
            }
        });
        jPanel1.add(fanta);
        fanta.setBounds(40, 210, 150, 50);

        summit.setBackground(new java.awt.Color(149, 171, 235));
        summit.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        summit.setText("SUMMIT");
        summit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        summit.setMaximumSize(new java.awt.Dimension(59, 23));
        summit.setMinimumSize(new java.awt.Dimension(59, 23));
        summit.setPreferredSize(new java.awt.Dimension(59, 23));
        summit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                summitActionPerformed(evt);
            }
        });
        jPanel1.add(summit);
        summit.setBounds(210, 210, 150, 50);

        pepsi.setBackground(new java.awt.Color(104, 203, 227));
        pepsi.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        pepsi.setText("PEPSI");
        pepsi.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pepsi.setMaximumSize(new java.awt.Dimension(59, 23));
        pepsi.setMinimumSize(new java.awt.Dimension(59, 23));
        pepsi.setPreferredSize(new java.awt.Dimension(59, 23));
        pepsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pepsiActionPerformed(evt);
            }
        });
        jPanel1.add(pepsi);
        pepsi.setBounds(40, 280, 150, 50);

        sparkle.setBackground(new java.awt.Color(197, 220, 65));
        sparkle.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 24)); // NOI18N
        sparkle.setText("SPARKLE");
        sparkle.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        sparkle.setMaximumSize(new java.awt.Dimension(59, 23));
        sparkle.setMinimumSize(new java.awt.Dimension(59, 23));
        sparkle.setPreferredSize(new java.awt.Dimension(59, 23));
        sparkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sparkleActionPerformed(evt);
            }
        });
        jPanel1.add(sparkle);
        sparkle.setBounds(210, 280, 150, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SELECTED PRODUCT");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(360, 60, 280, 40);

        showProduct.setBackground(new java.awt.Color(0, 0, 0));
        showProduct.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        showProduct.setForeground(new java.awt.Color(255, 255, 0));
        showProduct.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        showProduct.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 2));
        jPanel1.add(showProduct);
        showProduct.setBounds(380, 100, 240, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PRICE");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(350, 140, 300, 40);

        showPrice.setBackground(new java.awt.Color(0, 0, 0));
        showPrice.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        showPrice.setForeground(new java.awt.Color(255, 255, 0));
        showPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        showPrice.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 2));
        jPanel1.add(showPrice);
        showPrice.setBounds(380, 180, 240, 40);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("SELECT QUANTITY");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(350, 230, 300, 20);

        showQty.setBackground(new java.awt.Color(0, 0, 0));
        showQty.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        showQty.setForeground(new java.awt.Color(255, 255, 0));
        showQty.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        showQty.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 2));
        showQty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showQtyActionPerformed(evt);
            }
        });
        jPanel1.add(showQty);
        showQty.setBounds(380, 260, 240, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("TOTAL PAYMENT");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(370, 360, 270, 40);

        showQty1.setBackground(new java.awt.Color(0, 0, 0));
        showQty1.setFont(new java.awt.Font("Verdana", 0, 20)); // NOI18N
        showQty1.setForeground(new java.awt.Color(255, 255, 0));
        showQty1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        showQty1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 2));
        jPanel1.add(showQty1);
        showQty1.setBounds(380, 400, 240, 40);

        jButton6.setBackground(new java.awt.Color(36, 52, 55));
        jButton6.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendinglegagzx/icons8-buy-for-coins-20.png"))); // NOI18N
        jButton6.setText("BUY");
        jButton6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(216, 203, 0), 2, true));
        jButton6.setContentAreaFilled(false);
        jButton6.setOpaque(true);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(390, 310, 110, 40);

        jButton7.setBackground(new java.awt.Color(36, 52, 55));
        jButton7.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendinglegagzx/icons8-clear-symbol-20.png"))); // NOI18N
        jButton7.setText("CLEAR");
        jButton7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(216, 203, 0), 2, true));
        jButton7.setContentAreaFilled(false);
        jButton7.setOpaque(true);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(510, 310, 100, 40);

        jButton8.setBackground(new java.awt.Color(36, 52, 55));
        jButton8.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendinglegagzx/icons8-reply-arrow-20.png"))); // NOI18N
        jButton8.setText("BACK");
        jButton8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(216, 203, 0), 2, true));
        jButton8.setContentAreaFilled(false);
        jButton8.setOpaque(true);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(440, 460, 110, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendinglegagzx/icons8-prism-46.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, -10, 60, 90);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendinglegagzx/icons8-logout-30 (1).png"))); // NOI18N
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(570, 480, 60, 50);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vendinglegagzx/222222.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.setOpaque(true);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(0, -20, 650, 590);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cokeActionPerformed
        String qty = JOptionPane.showInputDialog("Enter Quantity?(10 IS THE MAXIMUM)");

        int quantity = Integer.parseInt(qty);
        while(quantity>10||quantity<1)
        {
            JOptionPane.showMessageDialog(null,"Maximum is 10!");
            qty = JOptionPane.showInputDialog("Enter Quantity?(10 IS THE MAXIMUM)");
            quantity = Integer.parseInt(qty);
        }
        showQty.setText(""+qty);
        showProduct.setText("COKE");
        showPrice.setText("12.00");
    }//GEN-LAST:event_cokeActionPerformed

    private void jazzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jazzActionPerformed
        String qty = JOptionPane.showInputDialog("Enter Quantity?(10 IS THE MAXIMUM)");

        int quantity = Integer.parseInt(qty);
        while(quantity>10||quantity<1)
        {
            JOptionPane.showMessageDialog(null,"Maximum is 10!");
            qty = JOptionPane.showInputDialog("Enter Quantity?(10 IS THE MAXIMUM)");
            quantity = Integer.parseInt(qty);
        }
        showQty.setText(""+qty);
        showProduct.setText("JAZZ");
        showPrice.setText("8.00");
    }//GEN-LAST:event_jazzActionPerformed

    private void spriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spriteActionPerformed
        String qty = JOptionPane.showInputDialog("Enter Quantity?(10 IS THE MAXIMUM)");

        int quantity = Integer.parseInt(qty);
        while(quantity>10||quantity<1)
        {
            JOptionPane.showMessageDialog(null,"Maximum is 10!");
            qty = JOptionPane.showInputDialog("Enter Quantity?(10 IS THE MAXIMUM)");
            quantity = Integer.parseInt(qty);
        }
        showQty.setText(""+qty);
        showProduct.setText("SPRITE");
        showPrice.setText("11.00");
    }//GEN-LAST:event_spriteActionPerformed

    private void sevenUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenUpActionPerformed
        String qty = JOptionPane.showInputDialog("Enter Quantity?(10 IS THE MAXIMUM)");

        int quantity = Integer.parseInt(qty);
        while(quantity>10||quantity<1)
        {
            JOptionPane.showMessageDialog(null,"Maximum is 10!");
            qty = JOptionPane.showInputDialog("Enter Quantity?(10 IS THE MAXIMUM)");
            quantity = Integer.parseInt(qty);
        }
        showQty.setText(""+qty);
        showProduct.setText("SEVEN-UP");
        showPrice.setText("9.00");
    }//GEN-LAST:event_sevenUpActionPerformed

    private void fantaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fantaActionPerformed
        String qty = JOptionPane.showInputDialog("Enter Quantity?(10 IS THE MAXIMUM)");

        int quantity = Integer.parseInt(qty);
        while(quantity>10||quantity<1)
        {
            JOptionPane.showMessageDialog(null,"Maximum is 10!");
            qty = JOptionPane.showInputDialog("Enter Quantity?(10 IS THE MAXIMUM)");
            quantity = Integer.parseInt(qty);
        }
        showQty.setText(""+qty);
        showProduct.setText("FANTA");
        showPrice.setText("11.00");
    }//GEN-LAST:event_fantaActionPerformed

    private void summitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_summitActionPerformed
         String qty = JOptionPane.showInputDialog("Enter Quantity?(10 IS THE MAXIMUM)");
        
        
        int quantity = Integer.parseInt(qty);
        while(quantity>10||quantity<1)
        {
            JOptionPane.showMessageDialog(null,"Maximum is 10!");
            qty = JOptionPane.showInputDialog("Enter Quantity?(10 IS THE MAXIMUM)");
            quantity = Integer.parseInt(qty);      
        }
        showProduct.setText("SUMMIT");
        showPrice.setText("10.00");
        showQty.setText(""+qty);       
    }//GEN-LAST:event_summitActionPerformed

    private void pepsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pepsiActionPerformed
        String qty = JOptionPane.showInputDialog("Enter Quantity?(10 IS THE MAXIMUM)");

        int quantity = Integer.parseInt(qty);
        while(quantity>10||quantity<1)
        {
            JOptionPane.showMessageDialog(null,"Maximum is 10!");
            qty = JOptionPane.showInputDialog("Enter Quantity?(10 IS THE MAXIMUM)");
            quantity = Integer.parseInt(qty);
        }
        showQty.setText(""+qty);
        showProduct.setText("PEPSI");
        showPrice.setText("12.00");
    }//GEN-LAST:event_pepsiActionPerformed

    private void sparkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sparkleActionPerformed
        String qty = JOptionPane.showInputDialog("Enter Quantity?(10 IS THE MAXIMUM)");

        int quantity = Integer.parseInt(qty);
        while(quantity>10||quantity<1)
        {
            JOptionPane.showMessageDialog(null,"Maximum is 10!");
            qty = JOptionPane.showInputDialog("Enter Quantity?(10 IS THE MAXIMUM)");
            quantity = Integer.parseInt(qty);
        }
        showQty.setText(""+qty);
        showProduct.setText("SPARKLE");
        showPrice.setText("9.00");
    }//GEN-LAST:event_sparkleActionPerformed

    private void showQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_showQtyActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        double tprice = Double.parseDouble(showPrice.getText());
        double quant = Double.parseDouble(showQty.getText());

        double total = tprice * quant;
        showQty1.setText(""+total);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        showProduct.setText("");
        showPrice.setText("");
        showQty.setText("");
        showQty1.setText("");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
         NewJFrame3 kj = new NewJFrame3();
        kj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm if you want Exit", 
                "PRISM",
                JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton coke;
    private javax.swing.JButton fanta;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton jazz;
    public static javax.swing.JLabel name;
    private javax.swing.JButton pepsi;
    private javax.swing.JButton sevenUp;
    private javax.swing.JTextField showPrice;
    private javax.swing.JTextField showProduct;
    private javax.swing.JTextField showQty;
    private javax.swing.JTextField showQty1;
    private javax.swing.JButton sparkle;
    private javax.swing.JButton sprite;
    private javax.swing.JButton summit;
    // End of variables declaration//GEN-END:variables
 private void setIconImage() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icons8-prism-50.png")));
}}
